Authentification -> develop
StevenFA31/vite_whatsapp_weather_alert pull request #3
Opened 2023-08-24 09:05 UTC by StevenFA31

Creation of the new authentication page !

2023-08-24 09:39 UTC, MaximePawlakFr requested changes

2023-08-24 09:39 UTC, MaximePawlakFr commented on src/components/Header.tsx
> +                "http://localhost:3000/api/v1/users/logout",
localhost:3000 dépend de ton environnement.
Cela pourrait être mis dans une variable d'environnement.

2023-08-24 10:11 UTC, StevenFA31 commented on src/components/Header.tsx
> +                "http://localhost:3000/api/v1/users/logout",
Fait. Ajout de la variable d'environnement `localhostAPI` au lieu de `http://localhost:3000/`

2023-09-05 14:28 UTC, StevenFA31 commented on src/utils/constants.ts
>  export enum ClientPhoneNumber {
J'ai pas mal réfléchie à ton commentaire sur l'enum "ClientPhoneNumber" et j'ai peur que ça devienne un peu lourd à gérer côté code, surtout pour le peu d'informations qui en ressort.
Du coup, j'ai deux idées pour la gestion des noms des clients :
La première serait de saisir les noms directement en base de données.
La seconde serait d'utiliser le CRUD sur la route "Client" et de le faire via Postman ou un autre outil.

Ça permettra d'alléger le code et que tous ce passe directement dans les mains de l'utilisateur. 
Qu'en penses-tu ?

2023-09-05 14:44 UTC, MaximePawlakFr commented on src/utils/constants.ts
>  export enum ClientPhoneNumber {
C'est une très bonne idée, mais la question est : as-tu le temps ? Je pense que tu as d'autres priorités.
Mon commentaire visait surtout à sortir d'un fichier suivi par git des données "sensibles".
Commençons par la simplicité : mettre cela dans un ficher .env, pas suivi par git. On optimisera dans un second temps.

2023-09-05 15:50 UTC, MaximePawlakFr approved these changes

2023-09-06 07:44 UTC, merged